02/01/2019 09:37:37 AM Python Script is: main_sim.py
02/01/2019 09:37:37 AM study_name = W_bldg4en_cust
02/01/2019 09:37:37 AM Thread variable is False
02/01/2019 09:37:37 AM 


 Exception !!!!!!
Traceback (most recent call last):
  File "main_sim.py", line 2670, in main
    override_output=override_output)
  File "main_sim.py", line 2380, in __init__
    self.study_parameters = pd.read_csv(study_file)
  File "/Users/davidmartin/.local/share/virtualenvs/energy-sharing/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/davidmartin/.local/share/virtualenvs/energy-sharing/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/Users/davidmartin/.local/share/virtualenvs/energy-sharing/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/Users/davidmartin/.local/share/virtualenvs/energy-sharing/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/Users/davidmartin/.local/share/virtualenvs/energy-sharing/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'C:\\Users\\z5044992\\Documents\\MainDATA\\DATA_EN_5/studies/ww1/inputs/study_W_bldg4en_cust.csv' does not exist
